---
title: "Redox Walkthrough"
author: "Julian Stanley"
date: "September 27, 2018"
output: 
  html_document:
    code_folding: hide
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### E vs OxD

```{r}
# Define the Nernst function in terms of oxD
    E_OXD <- function(e0, oxD) {
      return(e0 - 12.71 * log((1-oxD)/oxD))
    }


# Generate oxD values between 0 and 1
oxD <- seq(0, 1, by = 0.001)
magOXD <- length(oxD)

# Generate values of E
# Assume: E0 = -265
E = E_OXD(rep(-265, each = magOXD), oxD)

# Set shape and plot
par(pty = 's')   

plot(oxD, E, type = 'l', main = "Cell potential as a \n function of fraction oxidized",
        ylab = expression('E'['roGFP']), xlab = expression('OxD'['roGFP']))

``` 

### OxD(Rmax) vs R

```{r}
# Define the fraction oxidized
OXD <- function(R, Rmin, Rmax, delta) {
      return (
        (R - Rmin)/((R - Rmin) + (delta*(Rmax - R)))
      )
}

# Get some colors
suppressWarnings(require(RColorBrewer, quietly = TRUE))
colors <- brewer.pal(n = 8, 'Dark2')

# Define constants and Rmax
# Assume: Minimum ratio of 0.667
# Assume: Delta of 0.171
Rmin <- 0.667
Rmax_values <- c(2, 4, 6, 8, 10, 12)
delta <- 0.171


# Generate inital values of R
R <- seq(Rmin, Rmax_values[1], by = 0.001)
magR <- length(R)

# Generate inital values of oxD
yOx = OXD(R, rep(Rmin, each = magR), 
        rep(Rmax_values[1], each = magR), 
        rep(delta, each = magR))
     
# Set margins and size
par(mar=c(5, 5, 5, 8), pty = 's') 

# Plot inital value
plot(R, yOx,
        type = 'l', main = "
     Fraction of molecules oxidized at intensity \n by measured ratio",
        ylab = expression('OxD'['roGFP']), xlab = expression('R'['410/470']),
        xlim = c(0, max(Rmax_values)),
     col = colors[1])


# Plot each variable Rmax
for (i in 2:length(Rmax_values)) {
  # Generate temporary values of R
  R <- seq(Rmin, Rmax_values[i], by = 0.001)
  magR <- length(R)

  # Generate temporary values of oxD
  yOx = OXD(R, rep(Rmin, each = magR), 
        rep(Rmax_values[i], each = magR), 
        rep(delta, each = magR))
  
  # Plot temporary value
  points(R, yOx, type = 'l', col = colors[i])
  
}

options(digits = 4)
legend("topright", title = expression(R['max']), inset=c(-0.35,0), xpd=TRUE, as.character(format(Rmax_values, nsmall = 3)), pch = rep(19, each = 6), col = colors[1:length(Rmax_values)])
```

### OxD(Rmin) vs R

```{r}
# Define the fraction oxidized
OXD <- function(R, Rmin, Rmax, delta) {
      return (
        (R - Rmin)/((R - Rmin) + (delta*(Rmax - R)))
      )
}

# Get some colors
suppressWarnings(require(RColorBrewer, quietly = TRUE))
colors <- brewer.pal(n = 8, 'Dark2')

# Define constants and Rmin
# Assume: Maximum ratio of 5.207
# Assume: Delta of 0.171
Rmin_values <- c(0.5, 1, 1.5, 2, 2.5, 3.0, 3.5, 4.0)
Rmax <- 5.207
delta <- 0.171


# Generate inital values of R
R <- seq(Rmin_values[1], Rmax, by = 0.001)
magR <- length(R)

# Generate inital values of oxD
yOx = OXD(R, rep(Rmin_values[1], each = magR), 
        rep(Rmax, each = magR), 
        rep(delta, each = magR))
     
# Set margins and size
par(mar=c(5, 5, 5, 8), pty = 's') 

# Plot inital value
plot(R, yOx,
        type = 'l', main = "
     Fraction of molecules oxidized at intensity \n by measured ratio",
        ylab = expression('OxD'['roGFP']), xlab = expression('R'['410/470']),
        xlim = c(0, Rmax),
     col = colors[1])


# Plot each variable Rmax
for (i in 2:length(Rmin_values)) {
  # Generate temporary values of R
  R <- seq(Rmin_values[i], Rmax, by = 0.001)
  magR <- length(R)

  # Generate temporary values of oxD
  yOx = OXD(R, rep(Rmin_values[i], each = magR), 
        rep(Rmax, each = magR), 
        rep(delta, each = magR))
  
  # Plot temporary value
  points(R, yOx, type = 'l', col = colors[i])
  
}

options(digits = 4)
legend("topright", title = expression(R['min']), inset=c(-0.35,0), xpd=TRUE, as.character(format(Rmin_values, nsmall = 3)), pch = rep(19, each = 6), col = colors[1:length(Rmin_values)])
```


### OxD(D470) vs R

```{r}
# Define the fraction oxidized
OXD <- function(R, Rmin, Rmax, delta) {
      return (
        (R - Rmin)/((R - Rmin) + (delta*(Rmax - R)))
      )
}

# Get some colors
suppressWarnings(require(RColorBrewer, quietly = TRUE))
colors <- brewer.pal(n = 8, 'Dark2')

# Define constants and delta
# Assume: Maximum ratio of 5.207 and minimum of 0.667
Rmin <- 0.667
Rmax <- 5.207
delta_values <- c(0.171, 0.5, 1.0, 2.0, 5.84)


# Generate values of R
R <- seq(Rmin, Rmax, by = 0.001)
magR <- length(R)

# Generate inital values of oxD
yOx = OXD(R, rep(Rmin, each = magR), 
        rep(Rmax, each = magR), 
        rep(delta_values[1], each = magR))
     
# Set margins and size
par(mar=c(5, 5, 5, 8), pty = 's') 

# Plot inital value
plot(R, yOx,
        type = 'l', main = "
     Fraction of molecules oxidized at intensity \n by measured ratio",
        ylab = expression('OxD'['roGFP']), xlab = expression('R'['410/470']),
        xlim = c(0, Rmax),
     col = colors[1])


# Plot each variable Rmax
for (i in 2:length(delta_values)) {
  # Generate temporary values of oxD
  yOx = OXD(R, rep(Rmin, each = magR), 
        rep(Rmax, each = magR), 
        rep(delta_values[i], each = magR))
  
  # Plot temporary value
  points(R, yOx, type = 'l', col = colors[i])
  
}

options(digits = 4)
legend("topright", title = expression(delta['470']), inset=c(-0.35,0), xpd=TRUE, as.character(format(delta_values, nsmall = 3)), pch = rep(19, each = 6), col = colors[1:length(delta_values)])
```

### E(Rmax) vs R

```{r}
# Define OxD
OXD <- function(R, Rmin, Rmax, delta) {
      return (
        (R - Rmin)/((R - Rmin) + (delta*(Rmax - R)))
      )
}
# Define the Nernst function in full terms
E_OXD <- function(e0, R, Rmin, Rmax, delta) {
      return(e0 - 12.71 * log((1-(OXD(R, Rmin, Rmax, delta)))
                              /(OXD(R, Rmin, Rmax, delta))))
    }

# Get some colors
suppressWarnings(require(RColorBrewer, quietly = TRUE))
colors <- brewer.pal(n = 8, 'Dark2')

# Define constants and Rmax
# Assume: Minimum ratio of 0.667
# Assume: Delta of 0.171
# Assume: e0 of -265
Rmin <- 0.667
Rmax_values <- c(2, 4, 6, 8, 10, 12)
delta <- 0.171
e0 <- -265


# Generate inital values of R
R <- seq(Rmin, Rmax_values[1], by = 0.001)
magR <- length(R)

# Generate inital values of oxD
yE = E_OXD(e0, R, rep(Rmin, each = magR), 
        rep(Rmax_values[1], each = magR), 
        rep(delta, each = magR))
     
# Set margins and size
par(mar=c(5, 5, 5, 8), pty = 's') 

# Plot inital value
plot(R, yE,
        type = 'l', main = "
     Half cell potential at intensity \n by measured ratio",
        ylab = expression('E'['roGFP']), xlab = expression('R'['410/470']),
        xlim = c(0, max(Rmax_values)),
     col = colors[1])


# Plot each variable Rmax
for (i in 2:length(Rmax_values)) {
  # Generate temporary values of R
  R <- seq(Rmin, Rmax_values[i], by = 0.001)
  magR <- length(R)

  # Generate temporary values of oxD
  yE = E_OXD(e0, R, rep(Rmin, each = magR), 
        rep(Rmax_values[i], each = magR), 
        rep(delta, each = magR))
  
  # Plot temporary value
  points(R, yE, type = 'l', col = colors[i])
  
}

options(digits = 4)
legend("topright", title = expression(R['max']), inset=c(-0.35,0), xpd=TRUE, as.character(format(Rmax_values, nsmall = 3)), pch = rep(19, each = 6), col = colors[1:length(Rmax_values)])
```

### E(Rmin) vs R

```{r}
# Define OxD
OXD <- function(R, Rmin, Rmax, delta) {
      return (
        (R - Rmin)/((R - Rmin) + (delta*(Rmax - R)))
      )
}
# Define the Nernst function in full terms
E_OXD <- function(e0, R, Rmin, Rmax, delta) {
      return(e0 - 12.71 * log((1-(OXD(R, Rmin, Rmax, delta)))
                              /(OXD(R, Rmin, Rmax, delta))))
    }

# Get some colors
suppressWarnings(require(RColorBrewer, quietly = TRUE))
colors <- brewer.pal(n = 8, 'Dark2')

# Define constants and Rmin
# Assume: Maximum ratio of 4.207
# Assume: Delta of 0.171
# Assume: e0 of -265
Rmin_values <- c(0.5, 1, 1.5, 2, 2.5, 3.0, 3.5, 4.0)
Rmax <- 5.207
delta <- 0.171
e0 <- -265


# Generate inital values of R
R <- seq(Rmin_values[1], Rmax, by = 0.001)
magR <- length(R)

# Generate inital values of oxD
yE = E_OXD(e0, R, rep(Rmin_values[1], each = magR), 
        rep(Rmax, each = magR), 
        rep(delta, each = magR))
     
# Set margins and size
par(mar=c(5, 5, 5, 8), pty = 's') 

# Plot inital value
plot(R, yE,
        type = 'l', main = "
     Half cell potential at intensity \n by measured ratio",
        ylab = expression('E'['roGFP']), xlab = expression('R'['410/470']),
        xlim = c(0, Rmax),
     col = colors[1])


# Plot each variable Rmax
for (i in 2:length(Rmin_values)) {
  # Generate temporary values of R
  R <- seq(Rmin_values[i], Rmax, by = 0.001)
  magR <- length(R)

  # Generate temporary values of oxD
  yE = E_OXD(e0, R, rep(Rmin_values[i], each = magR), 
        rep(Rmax, each = magR), 
        rep(delta, each = magR))
  
  # Plot temporary value
  points(R, yE, type = 'l', col = colors[i])
  
}

options(digits = 4)
legend("topright", title = expression(R['min']), inset=c(-0.35,0), xpd=TRUE, as.character(format(Rmin_values, nsmall = 3)), pch = rep(19, each = 6), col = colors[1:length(Rmin_values)])
```

### E(D470) vs R

### E(E0) vs R

### OxD vs R

### E vs R

### R -> R' reparameterization

### dE/dOxD vs OxD

### dOxD/dR' vs R'

### dE/dR' vs R'

### dOxD/dR' (D470) vs R'

### dE(D470)/dR' vs R'

### Empirical Errors

### Background vs Binning

### Image registration/edge effects 