---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r colors}
# Define coolwarm color gradient
coolwarm <- colorRampPalette(c(
  rgb( 60, 81,198, maxColorValue = 255),
  rgb( 61, 86,203, maxColorValue = 255),
  rgb( 63, 91,207, maxColorValue = 255),
  rgb( 65, 96,212, maxColorValue = 255),
  rgb( 67,101,216, maxColorValue = 255),
  rgb( 69,106,220, maxColorValue = 255),
  rgb( 71,111,224, maxColorValue = 255),
  rgb( 74,116,227, maxColorValue = 255),
  rgb( 76,121,231, maxColorValue = 255),
  rgb( 79,127,233, maxColorValue = 255),
  rgb( 83,132,236, maxColorValue = 255),
  rgb( 86,137,238, maxColorValue = 255),
  rgb( 90,143,240, maxColorValue = 255),
  rgb( 94,148,242, maxColorValue = 255),
  rgb( 99,153,243, maxColorValue = 255),
  rgb(103,159,244, maxColorValue = 255),
  rgb(109,164,244, maxColorValue = 255),
  rgb(114,169,245, maxColorValue = 255),
  rgb(120,174,245, maxColorValue = 255),
  rgb(126,179,245, maxColorValue = 255),
  rgb(132,184,244, maxColorValue = 255),
  rgb(139,188,243, maxColorValue = 255),
  rgb(146,193,242, maxColorValue = 255),
  rgb(153,197,241, maxColorValue = 255),
  rgb(161,201,239, maxColorValue = 255),
  rgb(169,205,238, maxColorValue = 255),
  rgb(177,209,236, maxColorValue = 255),
  rgb(186,212,233, maxColorValue = 255),
  rgb(195,215,231, maxColorValue = 255),
  rgb(204,218,229, maxColorValue = 255),
  rgb(214,221,226, maxColorValue = 255),
  rgb(223,223,223, maxColorValue = 255),
  rgb(235,218,215, maxColorValue = 255),
  rgb(245,213,207, maxColorValue = 255),
  rgb(255,206,198, maxColorValue = 255),
  rgb(255,192,184, maxColorValue = 255),
  rgb(255,180,170, maxColorValue = 255),
  rgb(255,168,159, maxColorValue = 255),
  rgb(255,157,148, maxColorValue = 255),
  rgb(255,147,139, maxColorValue = 255),
  rgb(255,138,130, maxColorValue = 255),
  rgb(255,129,122, maxColorValue = 255),
  rgb(255,121,115, maxColorValue = 255),
  rgb(255,113,109, maxColorValue = 255),
  rgb(255,105,103, maxColorValue = 255),
  rgb(255, 98, 98, maxColorValue = 255),
  rgb(255, 91, 93, maxColorValue = 255),
  rgb(255, 85, 89, maxColorValue = 255),
  rgb(255, 78, 85, maxColorValue = 255),
  rgb(255, 72, 81, maxColorValue = 255),
  rgb(255, 67, 78, maxColorValue = 255),
  rgb(255, 61, 75, maxColorValue = 255),
  rgb(255, 56, 72, maxColorValue = 255),
  rgb(255, 50, 70, maxColorValue = 255),
  rgb(255, 45, 67, maxColorValue = 255),
  rgb(255, 41, 65, maxColorValue = 255),
  rgb(252, 35, 62, maxColorValue = 255),
  rgb(242, 30, 58, maxColorValue = 255),
  rgb(233, 24, 55, maxColorValue = 255),
  rgb(223, 20, 51, maxColorValue = 255),
  rgb(212, 15, 48, maxColorValue = 255),
  rgb(202, 11, 44, maxColorValue = 255),
  rgb(191,  7, 41, maxColorValue = 255),
  rgb(180,  4, 38, maxColorValue = 255)))

colors4 <- c(
    rgb(151, 99, 172, maxColorValue = 255),
    rgb(214, 154, 191, maxColorValue = 255),
    rgb(249, 188, 112, maxColorValue = 255),
    rgb(224, 120, 34, maxColorValue = 255))

# Define plotting parameters
cex.lab <- 1.5
cex.axis <- 1.5
```

```{r equations}
# Define the fraction oxidized
OXD <- function(R, Rmin, Rmax, delta) {
      return (
        (R - Rmin)/((R - Rmin) + (delta*(Rmax - R)))
      )
}

# Define the redox potential
E <- function(e0, R, Rmin, Rmax, delta) {
  return(e0 - 12.71 * log((delta*Rmax - delta*R)/(R-Rmin)))
}

Eeff <- function(delta_470, e0) {
    return (
        e0 - 12.71 * log(delta_470)
    )
}

# Define the derivative of OxD
D_OXD <- function(R, Rmin, Rmax, delta) {
    return (
        (delta * (Rmax - Rmin)) /
            ((R * (delta - 1) - (delta * Rmax) + Rmin)^2)
    )
}

# Define the derivative of E
D_E <- function(R, Rmin, Rmax) {
    return(
        (-12.71*(Rmax-Rmin))/((R-Rmin)*(R-Rmax))
    )
}

# Define a percent error
Error_E <- function(R, Rmin, Rmax, delta, e0, percent_error) {
    answer <- c()
        for (Rind in R) {
            if((Rind * (1 - percent_error/100) >= Rmin) && (Rind * (1 + percent_error/100) <= Rmax)) {
                err <- max(
                abs(E(R = Rind, e0 = e0, Rmin = Rmin, Rmax = Rmax, delta = delta) 
                    - E(R = Rind * (1 + percent_error/100), e0 = e0, Rmin = Rmin, Rmax = Rmax, delta = delta)),
                abs(E(R = Rind, e0 = e0, Rmin = Rmin, Rmax = Rmax, delta = delta) 
                    - E(R = Rind * (1 - percent_error/100), e0 = e0, Rmin = Rmin, Rmax = Rmax, delta = delta))
                )
                answer <- c(answer, err)
            }
            
            else {
            
            answer <- c(answer, Inf)
            
            }
        }
        
    return(answer)
    
}
```

```{r combine-helper}
# Turn two pairs of lambda-emission spectra into a 3-column dataframe
combine <- function(ox_lambda, ox_value, red_lambda, red_value) {
    start <- max(ox_lambda[1], red_lambda[1])
    end <- min(ox_lambda[length(ox_lambda)], red_lambda[length(red_lambda)])
    
    range <- seq(start, end, by = 0.1)
    ox_value_new <- c()
    red_value_new <- c()
    
    for (lambda in range) {
        # Find the ox value closest to the lambda
        closest_value = Inf
        closest_index = NaN
        for (old_lambda_index in 1:length(ox_lambda)) {
            old_lambda_diff = abs(ox_lambda[old_lambda_index] - lambda)
            if (old_lambda_diff < closest_value) {
                closest_value = old_lambda_diff
                closest_index = old_lambda_index
            }
        }
        
        ox_value_new <- c(ox_value_new, ox_value[closest_index])
        
         # Find the red value closest to the lambda
        closest_value = Inf
        closest_index = NaN
        for (old_lambda_index in 1:length(red_lambda)) {
            old_lambda_diff = abs(red_lambda[old_lambda_index] - lambda)
            if (old_lambda_diff < closest_value) {
                closest_value = old_lambda_diff
                closest_index = old_lambda_index
            }
        }
        
        red_value_new <- c(red_value_new, red_value[closest_index])
        
    
    }
    
    return(data.frame(lambda = range, ox = ox_value_new, red = red_value_new))
    
}
```

```{r Initalize sensor function}
# Write a function that, given a sensor and two sets of lambda bands, returns a list of properties
# Sensor data format: 
initSensor <- function(sensor_data, lambda_1, lambda_2, e0) {
    # Clean data
    ox_lambda <- na.omit(sensor_data[[1]])
    ox_value <- na.omit(sensor_data[[2]])
    red_lambda <- na.omit(sensor_data[[3]])
    red_value <- na.omit(sensor_data[[4]])
    
    # Set delta
    delta <- mean(ox_value[ox_lambda >= lambda_2[1] & ox_lambda <= lambda_2[2]]) /  
                    mean(red_value[red_lambda >= lambda_2[1] & red_lambda <= lambda_2[2]])
    
    # Set Rmin and Rmax
    Rmin <- mean(red_value[red_lambda >= lambda_1[1] & red_lambda <= lambda_1[2]]) /  
                    mean(red_value[red_lambda >= lambda_2[1] & red_lambda <= lambda_2[2]])
    
    Rmax <- mean(ox_value[ox_lambda >= lambda_1[1] & ox_lambda <= lambda_1[2]]) /  
                    mean(ox_value[ox_lambda >= lambda_2[1] & ox_lambda <= lambda_2[2]])

    
    # Generate some R, OxD, and E values
    R <- seq(Rmin, Rmax, by = 0.001)
    OxD_values <- OXD(R, Rmin, Rmax, delta)
    E_values <- E(e0, R, Rmin, Rmax, delta)
    
    # Generate R' and R''
    RPrime <- R/Rmin
    RDoublePrime <- (R-Rmin)/(Rmax-Rmin)
    
    # Generate partial derivatives
    OxD_sen <- D_OXD(R = R, Rmin = Rmin, Rmax = Rmax, delta = delta)
    E_sen <- D_E(R = R, Rmin = Rmin, Rmax = Rmax)
    
    # Generate 5% errors
    Error5 <- Error_E(R = R, Rmin = Rmin, Rmax = Rmax, delta = delta, e0 = e0, percent_error = 5) 
    
    # Return the final list
    return(list(data = combine(ox_lambda, ox_value, red_lambda, red_value), e0 = e0, Eeff = Eeff(delta_470 = delta, e0 = e0),
                OxD_sen = OxD_sen, E_sen = E_sen, Error5 = Error5,
                delta = delta, Rmin = Rmin, Rmax = Rmax, R = R, OxD = OxD_values, E = E_values, 
                RPrime = RPrime, RDoublePrime = RDoublePrime))
}
```

```{r Initalize roGFP1, roGFP2}
# Import GFP1/2 data
gfp1_dat <- read.csv("rogfp1.csv", header = FALSE, stringsAsFactors = FALSE, 
                    fileEncoding="UTF-8-BOM")

gfp2_dat <- read.csv("rogfp2.csv", header = FALSE, stringsAsFactors=FALSE,
                     fileEncoding="UTF-8-BOM")

# Set known midpoint potentials
gfp1_e0 <-  -288
gfp2_e0 <- -272

# Get other properties
gfp1_prop <- initSensor(gfp1_dat, c(390, 410), c(470, 480), gfp1_e0)
gfp2_prop <- initSensor(gfp2_dat, c(390, 410), c(490, 500), gfp2_e0)
```

## Excitation-emission profiles

```{r Plot spectra, fig.align='center', fig.height = 5, fig.width = 10}
par(pty = 's', mfrow = c(1,2), mai = c(0.4, 0.8, 0.4, 0.8))

plot(gfp1_prop$data$ox ~ gfp1_prop$data$lambda, type = 'l', col = coolwarm(2)[1], main = "Emission spectrum of GFP1", xlab = expression(lambda), ylab = "Emission (relative)", bty = 'L')
points(gfp1_prop$data$red ~ gfp1_prop$data$lambda, type = 'l', col = coolwarm(2)[2])

legend("topright", xpd=TRUE, c("Oxidized", "Reduced"), pch = "-", lwd = 4, col = c(coolwarm(2)), cex = 1)

plot(gfp2_prop$data$ox ~ gfp2_prop$data$lambda, type = 'l', col = coolwarm(2)[1], main = "Emission spectrum of GFP2", xlab = expression(lambda), ylab = "Emission (relative)", bty = 'L', ylim = c(0, 30))
points(gfp2_prop$data$red ~ gfp2_prop$data$lambda, type = 'l', col = coolwarm(2)[2])

legend("topleft", xpd=TRUE, c("Oxidized", "Reduced"), pch = "-", lwd = 4, col = c(coolwarm(2)), cex = 1)
```

## Delta profiles
```{r Plot deltas, fig.align='center', fig.height = 5, fig.width = 10}
par(pty = 's', mfrow = c(1,2), mai = c(0.4, 0.8, 0.4, 0.8))

gfp1_deltas <- gfp1_prop$data$ox/gfp1_prop$data$red
plot(gfp1_deltas ~ gfp1_prop$data$lambda, type = 'l', col = 'black', main = "Delta profile of roGFP1", xlab = expression(lambda), ylab = expression(delta), bty = 'L')

gfp2_deltas <- gfp2_prop$data$ox/gfp2_prop$data$red
plot(gfp2_deltas ~ gfp2_prop$data$lambda, type = 'l', col = 'black', main = "Delta profile of roGFP2", xlab = expression(lambda), ylab = expression(delta), bty = 'L')
      
values <- (data.frame(
    c("Delta ~ 1", "Delta minimized", "Delta maximized"),
    
    c(gfp1_prop$data$lambda[which.min(abs(gfp1_deltas - 1))],
      gfp1_prop$data$lambda[which.min(gfp1_deltas)],
      gfp1_prop$data$lambda[which.max(gfp1_deltas)]),
    
    c(gfp2_prop$data$lambda[which.min(abs(gfp2_deltas - 1))],
      gfp2_prop$data$lambda[which.min(gfp2_deltas)],
      gfp2_prop$data$lambda[which.max(gfp2_deltas)])
    ))

colnames(values) <- c("Characteristic", "GFP1", "GFP2")
knitr::kable(values, caption = "Table 1: Approximate delta-wavelength values for GFP1 and GFP2 sensors")
```

Choose two sets of wavelengths for each sensor.

For GFP1: 

* Use $\frac{380 +/- 5 nm}{435 +/- 5 nm}$ for isobestic
* Use $\frac{380 +/- 5 nm}{460 +/- 5 nm}$ for maximum total dynamic range

For GFP2:

* Use $\frac{360 +/- 5 nm}{425 +/- 5 nm}$ for isobestic
* Use $\frac{360 +/- 5 nm}{450 +/- 5 nm}$ for maximum total dynamic range



```{r Initalize two sets of roGFP1 and roGFP2}
# Set known midpoint potentials
gfp1_e0 <-  -288
gfp2_e0 <- -272

# Get other properties
gfp1_iso_prop <- initSensor(gfp1_dat, c(375, 385), c(430, 440), gfp1_e0)
gfp1_max_prop <- initSensor(gfp1_dat, c(375, 385), c(455, 465), gfp1_e0)

gfp2_iso_prop <- initSensor(gfp2_dat, c(355, 365), c(420, 430), gfp2_e0)
gfp2_max_prop <- initSensor(gfp2_dat, c(355, 365), c(445, 455), gfp2_e0)


# Print some properties
values <- (data.frame(
    c("Delta", "Rmin", "Rmax", "E0", "Adjusted E0",
      "Dynamic Range", "Fold Change"), 
    
    c(round(gfp1_iso_prop$delta, 1),
      round(gfp1_iso_prop$Rmin, 1),
      round(gfp1_iso_prop$Rmax, 1),
      gfp1_e0,
      round(Eeff(gfp1_iso_prop$delta, gfp1_e0), 1),
      round(gfp1_iso_prop$Rmax - gfp1_iso_prop$Rmin, 1), 
      round(gfp1_iso_prop$Rmax/gfp1_iso_prop$Rmin, 1)),
    
    c(round(gfp1_max_prop$delta, 1), 
      round(gfp1_max_prop$Rmin, 1),
      round(gfp1_max_prop$Rmax, 1),
      gfp1_e0, 
      round(Eeff(gfp1_max_prop$delta, gfp1_e0), 1),
      round(gfp1_max_prop$Rmax - gfp1_max_prop$Rmin, 1), 
      round(gfp1_max_prop$Rmax/gfp1_max_prop$Rmin, 1)),
    
    c(round(gfp2_iso_prop$delta, 1), 
      round(gfp2_iso_prop$Rmin, 2), 
      round(gfp2_iso_prop$Rmax, 1), 
      gfp2_e0, 
      round(Eeff(gfp2_iso_prop$delta, gfp2_e0), 1),
      round(gfp2_iso_prop$Rmax - gfp2_iso_prop$Rmin, 1), 
      round(gfp2_iso_prop$Rmax/gfp2_iso_prop$Rmin, 1)),
    
    c(round(gfp2_max_prop$delta, 1), 
      round(gfp2_max_prop$Rmin, 2), 
      round(gfp2_max_prop$Rmax, 1),
      gfp2_e0, 
      round(Eeff(gfp2_max_prop$delta, gfp2_e0), 1),
      round(gfp2_max_prop$Rmax - gfp2_max_prop$Rmin, 1), 
      round(gfp2_max_prop$Rmax/gfp2_max_prop$Rmin, 1))
    ))

colnames(values) <- c("Characteristic", "GFP1 Isobestic", "GFP1 Max", "GFP2 Isobestic", "GFP2 Max")
knitr::kable(values, caption = "Table 2: Characteristics of GFP1 and GFP2 sensors")
```

```{r Characterize E0 and delta, fig.align='center', fig.height = 5, fig.width = 10}
par(pty = 's', mfrow = c(1,2), mai = c(0.4, 1.1, 0.4, 0.8))
plot(gfp1_max_prop$Eeff - gfp1_max_prop$e0 ~ log(gfp1_max_prop$delta), ylim = c(-30, 30), xlim = c(-2, 2), col = colors4[2],pch = 16, cex = 2, ylab = expression('E'^'0' - 'E'['eff']), xlab = expression(ln(delta)))
points(gfp1_iso_prop$Eeff - gfp1_iso_prop$e0 ~ log(gfp1_iso_prop$delta), col = colors4[1],pch = 16, cex = 2)
points(gfp2_max_prop$Eeff - gfp2_max_prop$e0 ~ log(gfp2_max_prop$delta), col= colors4[3],pch = 16, cex = 2)
points(gfp2_iso_prop$Eeff - gfp2_iso_prop$e0 ~ log(gfp2_iso_prop$delta), col = colors4[4],pch = 16, cex = 2)


deltas <- seq(exp(-2), exp(2))
lines(lowess(Eeff(deltas, 300) - 300 ~ log(deltas)), col = "black")

legend("topright", xpd=TRUE, c("GFP1 Max", "GFP1 Iso", "GFP2 Max","GFP2 Iso", 'RT/2F'), pch = "-", lwd = 4, col = c(colors4[2], colors4[1], colors4[3], colors4[4], 'black'), cex = 1)

plot((gfp1_max_prop$Rmax-gfp1_max_prop$Rmin) ~ log(gfp1_max_prop$delta), ylim = c(0, 30), xlim = c(-2, 2), col = colors4[2],pch = 16, cex = 2, ylab = expression(R[max]-R[min]), xlab = expression(ln(delta)))
points((gfp1_iso_prop$Rmax-gfp1_iso_prop$Rmin) ~ log(gfp1_iso_prop$delta), col = colors4[1],pch = 16, cex = 2)
points((gfp2_max_prop$Rmax-gfp2_max_prop$Rmin) ~ log(gfp2_max_prop$delta), col= colors4[3],pch = 16, cex = 2)
points((gfp2_iso_prop$Rmax-gfp2_iso_prop$Rmin) ~ log(gfp2_iso_prop$delta), col = colors4[4],pch = 16, cex = 2)



legend("topright", xpd=TRUE, c("GFP1 Max", "GFP1 Iso", "GFP2 Max","GFP2 Iso"), pch = "-", lwd = 4, col = c(colors4[2], colors4[1], colors4[3], colors4[4]), cex = 1)

```

## Fraction oxidized and redox potential
```{r OxD and E, fig.align='center', fig.height = 5, fig.width = 10}
par(pty = 's', mfrow = c(1,2), mai = c(0.4, 0.8, 0.4, 0.8))
plot(gfp2_max_prop$OxD ~ gfp2_max_prop$RDoublePrime, type = 'l', col = colors4[3], lwd = 2, bty = 'l', xlab = "R''", ylab = "Fraction of sensors oxidized")
points(gfp2_iso_prop$OxD ~ gfp2_iso_prop$RDoublePrime, type = 'l', col = colors4[4], lwd = 2)
points(gfp1_max_prop$OxD ~ gfp1_max_prop$RDoublePrime, type = 'l', col = colors4[2], lwd = 2)
points(gfp1_iso_prop$OxD ~ gfp1_iso_prop$RDoublePrime, type = 'l', col = colors4[1], lwd = 2)

legend("bottomright", xpd=TRUE, c("GFP1 Max", "GFP1 Iso", "GFP2 Max","GFP2 Iso"), pch = "-", lwd = 4, col = c(colors4[2], colors4[1], colors4[3], colors4[4]), cex = 1)
           
plot(gfp2_max_prop$E ~ gfp2_max_prop$RDoublePrime, type = 'l', ylim = c(-325, -200), col = colors4[3], lwd = 2, bty = 'l', xlab = "R''", ylab = expression('E'['GSH']))
points(gfp2_iso_prop$E ~ gfp2_iso_prop$RDoublePrime, type = 'l', lwd = 2, col = colors4[4])
points(gfp1_max_prop$E ~ gfp1_max_prop$RDoublePrime, type = 'l', lwd = 2, col = colors4[2])
points(gfp1_iso_prop$E ~ gfp1_iso_prop$RDoublePrime, type = 'l', lwd = 2, col = colors4[1])

legend("bottomright", xpd=TRUE, c("GFP1 Max", "GFP1 Iso", "GFP2 Max","GFP2 Iso"), pch = "-", lwd = 4, col = c(colors4[2], colors4[1], colors4[3], colors4[4]), cex = 1)
```

```{r Sensitivity of E and OxD,  fig.align='center', fig.height = 5, fig.width = 10}
par(pty = 's', mfrow = c(1,2), mai = c(0.4, 0.8, 0.4, 0.8))
plot(gfp1_max_prop$OxD_sen ~ gfp1_max_prop$RDoublePrime, type = 'l', col = colors4[2], lwd = 2, bty = 'l', xlab = "R''", ylab = "Relative sensitivity of OxD", ylim = c(0, 5))
points(gfp1_iso_prop$OxD_sen ~ gfp1_iso_prop$RDoublePrime, type = 'l', col = colors4[1], lwd = 2)
points(gfp2_max_prop$OxD_sen ~ gfp2_max_prop$RDoublePrime, type = 'l', col = colors4[3], lwd = 2)
points(gfp2_iso_prop$OxD_sen ~ gfp2_iso_prop$RDoublePrime, type = 'l', col = colors4[4],lwd = 2)

legend("topright", xpd=TRUE, c("GFP1 Max", "GFP1 Iso", "GFP2 Max","GFP2 Iso"), pch = "-", lwd = 4, col = c(colors4[2], colors4[1], colors4[3], colors4[4]), cex = 1)

plot(gfp1_max_prop$E_sen ~ gfp1_max_prop$RDoublePrime, type = 'l', col = colors4[2], lwd = 2, bty = 'l', xlab = "R''", ylab = "Relative sensitivity of E", ylim = c(0, 200))
points(gfp1_iso_prop$E_sen ~ gfp1_iso_prop$RDoublePrime, type = 'l', col = colors4[1], lwd = 2)
points(gfp2_max_prop$E_sen ~ gfp2_max_prop$RDoublePrime, type = 'l', col = colors4[3], lwd = 2)
points(gfp2_iso_prop$E_sen ~ gfp2_iso_prop$RDoublePrime, type = 'l', col = colors4[4],lwd = 2)

legend("top", xpd=TRUE, c("GFP1 Max", "GFP1 Iso", "GFP2 Max","GFP2 Iso"), pch = "-", lwd = 4, col = c(colors4[2], colors4[1], colors4[3], colors4[4]), cex = 1)
```

## Sensitivity given 5% error in R
```{r, fig.align='center', fig.height = 5, fig.width = 10}
par(pty = 's', mfrow = c(1,2), mai = c(0.4, 0.8, 0.4, 0.8))

plot(gfp1_max_prop$E ~ gfp1_max_prop$Error5, type = 'l', xlim = c(0, 20), ylim = c(-350, -150), col = colors4[2], lwd = 2, bty = 'l', xlab = "Minimum Error", ylab = expression(E[GSH]))
points(gfp1_iso_prop$E ~ gfp1_iso_prop$Error5, type = 'l', col = colors4[1], lwd = 2)
points(gfp2_max_prop$E ~ gfp2_max_prop$Error5, type = 'l', col = colors4[3], lwd = 2)
points(gfp2_iso_prop$E ~ gfp2_iso_prop$Error5, type = 'l', col = colors4[4], lwd = 2)

legend("top", xpd=TRUE, c("GFP1 Max", "GFP1 Iso", "GFP2 Max","GFP2 Iso"), pch = "-", lwd = 4, col = c(colors4[2], colors4[1], colors4[3], colors4[4]), cex = 1)

plot(min(gfp1_max_prop$Error5) ~ I(gfp1_max_prop$Rmax/gfp1_max_prop$Rmin), col = colors4[2], bty = 'l',pch = 16, cex = 2, ylim = c(0, 10), xlim = c(0, 40), ylab = "Minimum Error (mV)", xlab = expression(R[Max]/R[Min]))
points(min(gfp1_iso_prop$Error5) ~ I(gfp1_iso_prop$Rmax/gfp1_iso_prop$Rmin), col = colors4[1],pch = 16, cex = 2)
points(min(gfp2_max_prop$Error5) ~ I(gfp2_max_prop$Rmax/gfp2_max_prop$Rmin), col = colors4[3],pch = 16, cex = 2)
points(min(gfp2_iso_prop$Error5) ~ I(gfp2_iso_prop$Rmax/gfp2_iso_prop$Rmin), col = colors4[4],pch = 16, cex = 2)

legend("topright", xpd=TRUE, c("GFP1 Max", "GFP1 Iso", "GFP2 Max","GFP2 Iso"), pch = "-", lwd = 4, col = c(colors4[2], colors4[1], colors4[3], colors4[4]), cex = 1)
```
