---
output:
    html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r colors}
# Define coolwarm color gradient
coolwarm <- colorRampPalette(c(
  rgb( 60, 81,198, maxColorValue = 255),
  rgb( 61, 86,203, maxColorValue = 255),
  rgb( 63, 91,207, maxColorValue = 255),
  rgb( 65, 96,212, maxColorValue = 255),
  rgb( 67,101,216, maxColorValue = 255),
  rgb( 69,106,220, maxColorValue = 255),
  rgb( 71,111,224, maxColorValue = 255),
  rgb( 74,116,227, maxColorValue = 255),
  rgb( 76,121,231, maxColorValue = 255),
  rgb( 79,127,233, maxColorValue = 255),
  rgb( 83,132,236, maxColorValue = 255),
  rgb( 86,137,238, maxColorValue = 255),
  rgb( 90,143,240, maxColorValue = 255),
  rgb( 94,148,242, maxColorValue = 255),
  rgb( 99,153,243, maxColorValue = 255),
  rgb(103,159,244, maxColorValue = 255),
  rgb(109,164,244, maxColorValue = 255),
  rgb(114,169,245, maxColorValue = 255),
  rgb(120,174,245, maxColorValue = 255),
  rgb(126,179,245, maxColorValue = 255),
  rgb(132,184,244, maxColorValue = 255),
  rgb(139,188,243, maxColorValue = 255),
  rgb(146,193,242, maxColorValue = 255),
  rgb(153,197,241, maxColorValue = 255),
  rgb(161,201,239, maxColorValue = 255),
  rgb(169,205,238, maxColorValue = 255),
  rgb(177,209,236, maxColorValue = 255),
  rgb(186,212,233, maxColorValue = 255),
  rgb(195,215,231, maxColorValue = 255),
  rgb(204,218,229, maxColorValue = 255),
  rgb(214,221,226, maxColorValue = 255),
  rgb(223,223,223, maxColorValue = 255),
  rgb(235,218,215, maxColorValue = 255),
  rgb(245,213,207, maxColorValue = 255),
  rgb(255,206,198, maxColorValue = 255),
  rgb(255,192,184, maxColorValue = 255),
  rgb(255,180,170, maxColorValue = 255),
  rgb(255,168,159, maxColorValue = 255),
  rgb(255,157,148, maxColorValue = 255),
  rgb(255,147,139, maxColorValue = 255),
  rgb(255,138,130, maxColorValue = 255),
  rgb(255,129,122, maxColorValue = 255),
  rgb(255,121,115, maxColorValue = 255),
  rgb(255,113,109, maxColorValue = 255),
  rgb(255,105,103, maxColorValue = 255),
  rgb(255, 98, 98, maxColorValue = 255),
  rgb(255, 91, 93, maxColorValue = 255),
  rgb(255, 85, 89, maxColorValue = 255),
  rgb(255, 78, 85, maxColorValue = 255),
  rgb(255, 72, 81, maxColorValue = 255),
  rgb(255, 67, 78, maxColorValue = 255),
  rgb(255, 61, 75, maxColorValue = 255),
  rgb(255, 56, 72, maxColorValue = 255),
  rgb(255, 50, 70, maxColorValue = 255),
  rgb(255, 45, 67, maxColorValue = 255),
  rgb(255, 41, 65, maxColorValue = 255),
  rgb(252, 35, 62, maxColorValue = 255),
  rgb(242, 30, 58, maxColorValue = 255),
  rgb(233, 24, 55, maxColorValue = 255),
  rgb(223, 20, 51, maxColorValue = 255),
  rgb(212, 15, 48, maxColorValue = 255),
  rgb(202, 11, 44, maxColorValue = 255),
  rgb(191,  7, 41, maxColorValue = 255),
  rgb(180,  4, 38, maxColorValue = 255)))

colors4 <- c(
    rgb(151, 99, 172, maxColorValue = 255),
    rgb(214, 154, 191, maxColorValue = 255),
    rgb(249, 188, 112, maxColorValue = 255),
    rgb(224, 120, 34, maxColorValue = 255))

# Define plotting parameters
cex.lab <- 1.5
cex.axis <- 1.5
```

```{r equations}
# Define the fraction oxidized
OXD <- function(R, Rmin, Rmax, delta) {
      return (
        (R - Rmin)/((R - Rmin) + (delta*(Rmax - R)))
      )
}

# Define the redox potential
E <- function(e0, R, Rmin, Rmax, delta) {
  return(e0 - 12.71 * log((delta*Rmax - delta*R)/(R-Rmin)))
}

Eeff <- function(delta_470, e0) {
    return (
        e0 - 12.71 * log(delta_470)
    )
}

# Define the derivative of OxD
D_OXD <- function(R, Rmin, Rmax, delta) {
    return (
        (delta * (Rmax - Rmin)) /
            ((R * (delta - 1) - (delta * Rmax) + Rmin)^2)
    )
}

# Define the derivative of E
D_E <- function(R, Rmin, Rmax) {
    return(
        (-12.71*(Rmax-Rmin))/((R-Rmin)*(R-Rmax))
    )
}

# Define a percent error
Error_E <- function(R, Rmin, Rmax, delta, e0, percent_error) {
    answer <- c()
        for (Rind in R) {
            if((Rind * (1 - percent_error/100) >= Rmin) && (Rind * (1 + percent_error/100) <= Rmax)) {
                err <- max(
                abs(E(R = Rind, e0 = e0, Rmin = Rmin, Rmax = Rmax, delta = delta) 
                    - E(R = Rind * (1 + percent_error/100), e0 = e0, Rmin = Rmin, Rmax = Rmax, delta = delta)),
                abs(E(R = Rind, e0 = e0, Rmin = Rmin, Rmax = Rmax, delta = delta) 
                    - E(R = Rind * (1 - percent_error/100), e0 = e0, Rmin = Rmin, Rmax = Rmax, delta = delta))
                )
                answer <- c(answer, err)
            }
            
            else {
            
            answer <- c(answer, Inf)
            
            }
        }
        
    return(answer)
    
}
```

```{r combine-helper}
# Turn two pairs of lambda-emission spectra into a 3-column dataframe
combine <- function(ox_lambda, ox_value, red_lambda, red_value) {
    start <- max(ox_lambda[1], red_lambda[1])
    end <- min(ox_lambda[length(ox_lambda)], red_lambda[length(red_lambda)])
    
    range <- seq(start, end, by = 0.1)
    ox_value_new <- c()
    red_value_new <- c()
    
    for (lambda in range) {
        # Find the ox value closest to the lambda
        closest_value = Inf
        closest_index = NaN
        for (old_lambda_index in 1:length(ox_lambda)) {
            old_lambda_diff = abs(ox_lambda[old_lambda_index] - lambda)
            if (old_lambda_diff < closest_value) {
                closest_value = old_lambda_diff
                closest_index = old_lambda_index
            }
        }
        
        ox_value_new <- c(ox_value_new, ox_value[closest_index])
        
         # Find the red value closest to the lambda
        closest_value = Inf
        closest_index = NaN
        for (old_lambda_index in 1:length(red_lambda)) {
            old_lambda_diff = abs(red_lambda[old_lambda_index] - lambda)
            if (old_lambda_diff < closest_value) {
                closest_value = old_lambda_diff
                closest_index = old_lambda_index
            }
        }
        
        red_value_new <- c(red_value_new, red_value[closest_index])
        
    
    }
    
    return(data.frame(lambda = range, ox = ox_value_new, red = red_value_new))
    
}
```

```{r Initalize sensor function}
# Write a function that, given a sensor and two sets of lambda bands, returns a list of properties
# Sensor data format: 
initSensor <- function(sensor_data, lambda_1, lambda_2, e0) {
    # Clean data
    ox_lambda <- na.omit(sensor_data[[1]])
    ox_value <- na.omit(sensor_data[[2]])
    red_lambda <- na.omit(sensor_data[[3]])
    red_value <- na.omit(sensor_data[[4]])
    
    # Set delta
    delta <- mean(ox_value[ox_lambda >= lambda_2[1] & ox_lambda <= lambda_2[2]]) /  
                    mean(red_value[red_lambda >= lambda_2[1] & red_lambda <= lambda_2[2]])
    
    # Set Rmin and Rmax
    Rmin <- mean(red_value[red_lambda >= lambda_1[1] & red_lambda <= lambda_1[2]]) /  
                    mean(red_value[red_lambda >= lambda_2[1] & red_lambda <= lambda_2[2]])
    
    Rmax <- mean(ox_value[ox_lambda >= lambda_1[1] & ox_lambda <= lambda_1[2]]) /  
                    mean(ox_value[ox_lambda >= lambda_2[1] & ox_lambda <= lambda_2[2]])

    
    # Generate some R, OxD, and E values
    R <- seq(Rmin, Rmax, by = 0.001)
    OxD_values <- OXD(R, Rmin, Rmax, delta)
    E_values <- E(e0, R, Rmin, Rmax, delta)
    
    # Generate R' and R''
    RPrime <- R/Rmin
    RDoublePrime <- (R-Rmin)/(Rmax-Rmin)
    
    # Generate partial derivatives
    OxD_sen <- D_OXD(R = R, Rmin = Rmin, Rmax = Rmax, delta = delta)
    E_sen <- D_E(R = R, Rmin = Rmin, Rmax = Rmax)
    
    # Generate 5% errors
    Error5 <- Error_E(R = R, Rmin = Rmin, Rmax = Rmax, delta = delta, e0 = e0, percent_error = 5) 
    
    # Return the final list
    return(list(data = combine(ox_lambda, ox_value, red_lambda, red_value), e0 = e0, Eeff = Eeff(delta_470 = delta, e0 = e0),
                OxD_sen = OxD_sen, E_sen = E_sen, Error5 = Error5,
                delta = delta, Rmin = Rmin, Rmax = Rmax, R = R, OxD = OxD_values, E = E_values, 
                RPrime = RPrime, RDoublePrime = RDoublePrime))
}
```

```{r Initalize roGFP1r12}
# Import GFP1/2 data
gfp1r12_dat <- read.csv("rogfp1r12.csv", header = FALSE, stringsAsFactors = FALSE, 
                    fileEncoding="UTF-8-BOM")


# Set known midpoint potentials
gfp1r12_e0 <-  -265

# Get other properties
gfp1r12_prop <- initSensor(gfp1r12_dat, c(400, 420), c(460, 480), gfp1r12_e0)
```

## Excitation-emission profiles

```{r Plot spectra, fig.align='center', fig.height=5, fig.width=5}
#png("rogfp1r12_spectra.jpg")

par(pty = 's', mfrow = c(1,1), mai = c(0.4, 0.8, 0.4, 0.8))

plot(gfp1r12_prop$data$ox ~ gfp1r12_prop$data$lambda, type = 'l', col = coolwarm(2)[2], main = "Emission spectrum of GFP1-R12", xlab = expression(lambda ~ (nm)), ylab = "Emission (relative)", bty = 'L')
points(gfp1r12_prop$data$red ~ gfp1r12_prop$data$lambda, type = 'l', col = coolwarm(2)[1])

legend("topright", xpd=TRUE, c("Oxidized", "Reduced"), pch = "-", lwd = 4, col = c(rev(coolwarm(2))), cex = 1)


#dev.off()
```

```{r plot-full-spectra}
par(pty = 's', mfrow = c(1,1), mai = c(1, 0.8, 0.4, 0.8))

gfp1r12_full <- read.csv("rogfp1r12_full.csv", header = FALSE, stringsAsFactors = FALSE, 
                    fileEncoding="UTF-8-BOM")
colors <- coolwarm(5)

plot(gfp1r12_full$V2 ~ gfp1r12_full$V1, type = 'l', col = colors[5], main = "Emission spectrum of GFP1-R12", xlab = expression(lambda ~ (nm)), ylab = "Emission (relative)", bty = 'L')

points(gfp1r12_full$V6 ~ gfp1r12_full$V1, type = 'l', col = colors[1])

points((gfp1r12_full$V2 * 0.75) + (gfp1r12_full$V6 * 0.25) ~ gfp1r12_full$V1, type = 'l', col = colors[4], lty = 'dashed')
points((gfp1r12_full$V2 * 0.50) + (gfp1r12_full$V6 * 0.50) ~ gfp1r12_full$V1, type = 'l', col = colors[3], lty = 'dashed')
points((gfp1r12_full$V2 * 0.25) + (gfp1r12_full$V6 * 0.75) ~ gfp1r12_full$V1, type = 'l', col = colors[2], lty = 'dashed')

legend("topright", title = "Percent Oxidized", xpd=TRUE, c("100", "75", "50", "25", "0"), pch = "-", lwd = 4, col = c(rev(colors)), cex = 1)

```

```{r plot-concentration, fig.align='center', fig.height=5, fig.width=5}
colors <- coolwarm(5)

par(pty = 's', mfrow = c(1,1))

concentration <- seq(0, 1, by = 0.01)

emission_ox <- concentration * 900
emission_red <- concentration * 600
emission_25ox <- concentration * 675
emission_50ox <- concentration * 750
emission_75ox <- concentration * 825

emission_ox_ratio <- (concentration * 900)  / (concentration * 150)
emission_red_ratio <- (concentration * 600) / (concentration * 400)
emission_25ox_ratio <- ( concentration * 675 ) / (concentration * 337.5)
emission_50ox_ratio <- (concentration * 750) / (concentration * 325)
emission_75ox_ratio <- (concentration * 825) / (concentration * 212.5)

plot(emission_ox ~ concentration, main = "Emission is a function of concentration", xlab = "roGFP concentration (relative)", ylab = "Emission readout (relative)", type = 'l', xlim = c(0, 1), ylim = c(1, 1000), col = colors[5], lwd = 3)
points(emission_25ox ~ concentration, type = 'l', col = colors[2], lwd = 3)
points(emission_50ox ~ concentration, type = 'l', col = colors[3], lwd = 3)
points(emission_75ox ~ concentration, type = 'l', col = colors[4], lwd = 3)
points(emission_red ~ concentration, type = 'l', col = colors[1], lwd = 3)

legend("topleft", title = "Percent Oxidized", xpd=TRUE, c("100", "75", "50", "25", "0"), pch = "-", lwd = 4, col = c(rev(colors)), cex = 1)

plot(emission_ox_ratio ~ concentration, main = "Ratiometric outputs are independent \n of concentration", xlab = "roGFP concentration (relative)", ylab = "R (relative)", type = 'l', xlim = c(0, 1), ylim = c(1,12), col = colors[5], lwd = 3)
points(emission_25ox_ratio ~ concentration, type = 'l', col = colors[2], lwd = 3)
points(emission_50ox_ratio ~ concentration, type = 'l', col = colors[3], lwd = 3)
points(emission_75ox_ratio ~ concentration, type = 'l', col = colors[4], lwd = 3)
points(emission_red_ratio ~ concentration, type = 'l', col = colors[1], lwd = 3)

legend("top", title = "Percent Oxidized", xpd=TRUE, c("100", "75", "50", "25", "0"), pch = "-", lwd = 4, col = c(rev(colors)), cex = 1)

```
## Delta profiles
```{r Plot deltas, fig.align='center', fig.height = 5, fig.width = 5}
par(pty = 's', mfrow = c(1,1), mai = c(0.4, 0.8, 0.4, 0.8))

gfp1r12_deltas <- gfp1r12_prop$data$ox/gfp1r12_prop$data$red
plot(gfp1r12_deltas ~ gfp1r12_prop$data$lambda, type = 'l', col = 'black', main = "Delta profile of roGFP1-R12", xlab = expression(lambda), ylab = expression(delta), bty = 'L')

      
values <- (data.frame(
    c("Delta ~ 1", "Delta minimized", "Delta maximized"),
    
    c(gfp1r12_prop$data$lambda[which.min(abs(gfp1r12_deltas - 1))],
      gfp1r12_prop$data$lambda[which.min(gfp1r12_deltas)],
      gfp1r12_prop$data$lambda[which.max(gfp1r12_deltas)])
    
    ))

colnames(values) <- c("Characteristic", "GFP1-R12")
knitr::kable(values, caption = "Approximate delta-wavelength values for GFP1-R12")
```

Choose two sets of wavelengths for each sensor.

For GFP1-R12: 

* Use $\frac{410 +/- 5 nm}{425 +/- 5 nm}$ for isobestic
* Use $\frac{410 +/- 5 nm}{470 +/- 5 nm}$ for maximum total dynamic range


```{r plot R12 at different deltas, fig.align='center', fig.height=5, fig.width=5}
colors <- coolwarm(6)

gfpr12_deltas_df <- data.frame(lambda = gfp1r12_prop$data$lambda, deltas = gfp1r12_deltas)

OXD_390 <- OXD(R = gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = subset(gfpr12_deltas_df$deltas, gfpr12_deltas_df$lambda > 389 & gfpr12_deltas_df$lambda < 391)[1])

OXD_410 <- OXD(R = gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = subset(gfpr12_deltas_df$deltas, gfpr12_deltas_df$lambda > 409 & gfpr12_deltas_df$lambda < 411)[1])

OXD_430 <- OXD(R = gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = subset(gfpr12_deltas_df$deltas, gfpr12_deltas_df$lambda > 429 & gfpr12_deltas_df$lambda < 431)[1])

OXD_450 <- OXD(R = gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = subset(gfpr12_deltas_df$deltas, gfpr12_deltas_df$lambda > 449 & gfpr12_deltas_df$lambda < 451)[1])

OXD_470 <- OXD(R = gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = subset(gfpr12_deltas_df$deltas, gfpr12_deltas_df$lambda > 469 & gfpr12_deltas_df$lambda < 471)[1])

OXD_490 <- OXD(R = gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = subset(gfpr12_deltas_df$deltas, gfpr12_deltas_df$lambda > 489 & gfpr12_deltas_df$lambda < 491)[1])

E_390 <- E(e0 = -265, R = gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = subset(gfpr12_deltas_df$deltas, gfpr12_deltas_df$lambda > 389 & gfpr12_deltas_df$lambda < 391)[1])

E_410 <- E(e0 = -265,R = gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = subset(gfpr12_deltas_df$deltas, gfpr12_deltas_df$lambda > 409 & gfpr12_deltas_df$lambda < 411)[1])

E_430 <- E(e0 = -265,R = gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = subset(gfpr12_deltas_df$deltas, gfpr12_deltas_df$lambda > 429 & gfpr12_deltas_df$lambda < 431)[1])

E_450 <- E(e0 = -265,R = gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = subset(gfpr12_deltas_df$deltas, gfpr12_deltas_df$lambda > 449 & gfpr12_deltas_df$lambda < 451)[1])

E_470 <- E(e0 = -265,R = gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = subset(gfpr12_deltas_df$deltas, gfpr12_deltas_df$lambda > 469 & gfpr12_deltas_df$lambda < 471)[1])

E_490 <- E(e0 = -265,R = gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = subset(gfpr12_deltas_df$deltas, gfpr12_deltas_df$lambda > 489 & gfpr12_deltas_df$lambda < 491)[1])

plot(OXD_490 ~ gfp1r12_prop$RDoublePrime, type = 'l', col = colors[1])
points(OXD_470 ~ gfp1r12_prop$RDoublePrime, type = 'l', col = colors[2])
points(OXD_450 ~ gfp1r12_prop$RDoublePrime, type = 'l', col = colors[3])
points(OXD_430 ~ gfp1r12_prop$RDoublePrime, type = 'l', col = colors[4])
points(OXD_410 ~ gfp1r12_prop$RDoublePrime, type = 'l', col = colors[5])
points(OXD_390 ~ gfp1r12_prop$RDoublePrime, type = 'l', col = colors[6])

legend("bottomright", title = expression(lambda[2]), xpd=TRUE, c("490", "470", "450", "430", "410", "390"), pch = "-", lwd = 4, col = colors, cex = 1)

plot(E_490 ~ gfp1r12_prop$RDoublePrime, type = 'l', col = colors[1])
points(E_470 ~ gfp1r12_prop$RDoublePrime, type = 'l', col = colors[2])
points(E_450 ~ gfp1r12_prop$RDoublePrime, type = 'l', col = colors[3])
points(E_430 ~ gfp1r12_prop$RDoublePrime, type = 'l', col = colors[4])
points(E_410 ~ gfp1r12_prop$RDoublePrime, type = 'l', col = colors[5])
points(E_390 ~ gfp1r12_prop$RDoublePrime, type = 'l', col = colors[6])
```

```{r Initalize two sets of roGFP1-R12}

# Get other properties
gfp1r12_iso_prop <- initSensor(gfp1r12_dat, c(400, 420), c(415, 435), gfp1r12_e0)
gfp1r12_max_prop <- initSensor(gfp1r12_dat, c(400, 420), c(460, 480), gfp1r12_e0)

# Print some properties
values <- (data.frame(
    c("Delta", "Rmin", "Rmax", "E0", "Adjusted E0",
      "Rmax-Rmin", "Rmax/Rmin"), 
    
    c(round(gfp1r12_iso_prop$delta, 1),
      round(gfp1r12_iso_prop$Rmin, 1),
      round(gfp1r12_iso_prop$Rmax, 1),
      gfp1r12_e0,
      round(Eeff(gfp1r12_iso_prop$delta, gfp1r12_e0), 1),
      round(gfp1r12_iso_prop$Rmax - gfp1r12_iso_prop$Rmin, 1), 
      round(gfp1r12_iso_prop$Rmax/gfp1r12_iso_prop$Rmin, 1)),
    
    c(round(gfp1r12_max_prop$delta, 1), 
      round(gfp1r12_max_prop$Rmin, 1),
      round(gfp1r12_max_prop$Rmax, 1),
      gfp1r12_e0, 
      round(Eeff(gfp1r12_max_prop$delta, gfp1r12_e0), 1),
      round(gfp1r12_max_prop$Rmax - gfp1r12_max_prop$Rmin, 1), 
      round(gfp1r12_max_prop$Rmax/gfp1r12_max_prop$Rmin, 1))
    ))

colnames(values) <- c("Characteristic", "GFP1 Isobestic", "GFP1 Max")
knitr::kable(values, caption = "Characteristics of GFP1-R12sensors")
```

```{r Characterize E0 and delta, fig.align='center', fig.height = 5, fig.width = 5}
par(pty = 's', mfrow = c(1,1), mai = c(0.4, 1.1, 0.4, 0.8))
plot(gfp1r12_max_prop$Eeff - gfp1r12_max_prop$e0 ~ log(gfp1r12_max_prop$delta), ylim = c(-30, 30), xlim = c(-2, 2), col = colors4[2],pch = 16, cex = 2, ylab = expression('E'^'0' - 'E'['eff']), xlab = expression(ln(delta)), main = "Delta determines deviation from midpoint")
points(gfp1r12_iso_prop$Eeff - gfp1r12_iso_prop$e0 ~ log(gfp1r12_iso_prop$delta), col = colors4[1],pch = 16, cex = 2)


deltas <- seq(exp(-2), exp(2))
lines(lowess(Eeff(deltas, 300) - 300 ~ log(deltas)), col = "black")

legend("topright", xpd=TRUE, c("GFP1-R12 Max", "GFP1-R12 Iso", 'RT/2F'), pch = "-", lwd = 4, col = c(colors4[2], colors4[1], 'black'), cex = 1)

plot((gfp1r12_max_prop$Rmax-gfp1r12_max_prop$Rmin) ~ log(gfp1r12_max_prop$delta), ylim = c(0, 30), xlim = c(-2, 2), col = colors4[2],pch = 16, cex = 2, ylab = expression(R[max]-R[min]), xlab = expression(ln(delta)), main = "Delta alters dynamic range")
points((gfp1r12_iso_prop$Rmax-gfp1r12_iso_prop$Rmin) ~ log(gfp1r12_iso_prop$delta), col = colors4[1],pch = 16, cex = 2)


legend("topright", xpd=TRUE, c("GFP1-R12 Max", "GFP1-R12 Iso"), pch = "-", lwd = 4, col = c(colors4[2], colors4[1], colors4[3], colors4[4]), cex = 1)

```

## Fraction oxidized and redox potential
```{r OxD and E, fig.align='center', fig.height = 5, fig.width = 5}
par(pty = 's', mfrow = c(1,1), mai = c(0.4, 0.8, 0.4, 0.8))
plot(gfp1r12_max_prop$OxD ~ gfp1r12_max_prop$RDoublePrime, type = 'l', col = colors4[2], lwd = 2, bty = 'l', xlab = "R''", ylab = "Fraction of sensors oxidized", main = "Normalized R -> fraction oxidized")
points(gfp1r12_iso_prop$OxD ~ gfp1r12_iso_prop$RDoublePrime, type = 'l', col = colors4[1], lwd = 2)

legend("bottomright", xpd=TRUE, c("GFP1 Max", "GFP1 Iso"), pch = "-", lwd = 4, col = c(colors4[2], colors4[1]), cex = 1)
           
plot(gfp1r12_max_prop$E ~ gfp1r12_max_prop$RDoublePrime, type = 'l', ylim = c(-325, -200), col = colors4[2], lwd = 2, bty = 'l', xlab = "R''", ylab = expression('E'['GSH']), main = "Normalized R -> half-cell potential")
points(gfp1r12_iso_prop$E ~ gfp1r12_iso_prop$RDoublePrime, type = 'l', lwd = 2, col = colors4[1])

legend("bottomright", xpd=TRUE, c("GFP1-R12 Max", "GFP1-R12 Iso"), pch = "-", lwd = 4, col = c(colors4[2], colors4[1]), cex = 1)
```

## Error in R

```{r precision in R, fig.align='center', fig.height = 5, fig.width = 5}
par(pty = 's', mfrow = c(1,1), mai = c(0.8, 0.8, 0.4, 0.8))

plot(gfp1r12_prop$R * 1.03 ~ gfp1r12_prop$R, type = 'l', xlab = "R", ylab = "Observed R")
points(gfp1r12_prop$R * 0.97 ~ gfp1r12_prop$R, type = 'l')

polygon(c(gfp1r12_prop$R, rev(gfp1r12_prop$R)), y = c(gfp1r12_prop$R * 1.03, rev(gfp1r12_prop$R * 0.97)), col = rgb(1, 0, 0, alpha = 1), density = 50, lty = "dotted")

legend("topleft", legend = c("R+3%", "R-3%", "Possible values"), col = c('black', 'black', rgb(1,0,0,alpha = 1)), lty = c(1, 1, 5))
```

```{r R to OxD precision, fig.align='center', fig.height = 5, fig.width = 5}
par(pty = 's', mfrow = c(1,1), mai = c(0.8, 0.8, 0.4, 0.8))
values_top <- OXD(gfp1r12_prop$R * 1.03, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = gfp1r12_prop$delta)
values_bottom <- OXD(gfp1r12_prop$R * 0.97, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = gfp1r12_prop$delta)

plot(values_top ~ gfp1r12_prop$R, type = 'l', xlab = "R", ylab = "Observed OxD")
points(values_bottom ~ gfp1r12_prop$R, type = 'l')

polygon(c(gfp1r12_prop$R, rev(gfp1r12_prop$R)), y = c(values_top, rev(values_bottom)), col = rgb(1, 0, 0, alpha = 1), density = 50, lty = "dotted")

legend("bottomright", legend = c("R+3%", "R-3%", "Possible values"), col = c('black', 'black', rgb(1,0,0,alpha = 1)), lty = c(1, 1, 5))
```

```{r R to E precision, fig.align='center', fig.height = 5, fig.width = 5}
par(pty = 's', mfrow = c(1,1), mai = c(0.8, 0.8, 0.4, 0.8))
values_bottom <- E(gfp1r12_prop$R * 1.03, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = gfp1r12_prop$delta, e0 = gfp1r12_prop$e0)
values_top <- E(gfp1r12_prop$R * 0.97, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = gfp1r12_prop$delta, e0 = gfp1r12_prop$e0)

plot(values_top ~ gfp1r12_prop$R, type = 'l', xlab = "R", ylab = "Observed E", ylim = c(-300, -200))
points(values_bottom ~ gfp1r12_prop$R, type = 'l')

limits <- c(100, 5497)
polygon(c(gfp1r12_prop$R[limits[1]:limits[2]], rev(gfp1r12_prop$R[limits[1]:limits[2]])), y = c(values_top[limits[1]:limits[2]], rev(values_bottom[limits[1]:limits[2]])), col = rgb(1, 0, 0, alpha = 1), density = 50, lty = "dotted")

legend("bottomright", legend = c("R+3%", "R-3%", "Possible values"), col = c('black', 'black', rgb(1,0,0,alpha = 1)), lty = c(1, 1, 5))
```

```{r E to E precision, fig.align='center', fig.height = 5, fig.width = 5}
par(pty = 's', mfrow = c(1,1), mai = c(0.8, 0.8, 0.4, 0.8))
values_bottom <- E(gfp1r12_prop$R * 1.03, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = gfp1r12_prop$delta, e0 = gfp1r12_prop$e0)
values_top <- E(gfp1r12_prop$R * 0.97, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = gfp1r12_prop$delta, e0 = gfp1r12_prop$e0)
values_actual <- E(gfp1r12_prop$R,  Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = gfp1r12_prop$delta, e0 = gfp1r12_prop$e0)

plot(values_top ~ values_actual, type = 'l', xlab = "Actual E", ylab = "Observed E", ylim = c(-300, -200), xlim = c(-300,-200))
points(values_bottom ~ values_actual, type = 'l')

limits <- c(100, 5497)
polygon(c(values_actual[limits[1]:limits[2]], rev(values_actual[limits[1]:limits[2]])), y = c(values_top[limits[1]:limits[2]], rev(values_bottom[limits[1]:limits[2]])), col = rgb(1, 0, 0, alpha = 1), density = 50, lty = "dotted")

legend("bottomright", legend = c("R+3%", "R-3%", "Possible values"), col = c('black', 'black', rgb(1,0,0,alpha = 1)), lty = c(1, 1, 5))
```

```{r E to E precision example, fig.align='center', fig.height = 5, fig.width = 5}
par(pty = 's', mfrow = c(1,1), mai = c(0.8, 0.8, 0.4, 0.8))
values_bottom <- E(gfp1r12_prop$R * 1.03, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = gfp1r12_prop$delta, e0 = gfp1r12_prop$e0)
values_top <- E(gfp1r12_prop$R * 0.97, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = gfp1r12_prop$delta, e0 = gfp1r12_prop$e0)
values_actual <- E(gfp1r12_prop$R,  Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = gfp1r12_prop$delta, e0 = gfp1r12_prop$e0)

plot(values_top ~ values_actual, type = 'l', xlab = "Actual E", ylab = "Observed E", ylim = c(-300, -200), xlim = c(-300,-200))
points(values_bottom ~ values_actual, type = 'l')

limits <- c(100, 5497)
polygon(c(values_actual[limits[1]:limits[2]], rev(values_actual[limits[1]:limits[2]])), y = c(values_top[limits[1]:limits[2]], rev(values_bottom[limits[1]:limits[2]])), col = rgb(1, 0, 0, alpha = 1), density = 50, lty = "dotted")

legend("bottomright", legend = c("R+3%", "R-3%", "Possible values"), col = c('black', 'black', rgb(1,0,0,alpha = 1)), lty = c(1, 1, 5))
```

### Here

```{r E to difference in E, fig.align='center', fig.height = 5, fig.width = 5}
par(pty = 's', mfrow = c(1,1), mai = c(0.8, 0.8, 0.4, 0.8))
values_bottom <- E(gfp1r12_prop$R * 1.03, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = gfp1r12_prop$delta, e0 = gfp1r12_prop$e0)
values_top <- E(gfp1r12_prop$R * 0.97, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = gfp1r12_prop$delta, e0 = gfp1r12_prop$e0)
values_actual <- E(gfp1r12_prop$R,  Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = gfp1r12_prop$delta, e0 = gfp1r12_prop$e0)

plot(abs(values_top - values_actual) ~ - values_actual, type = 'l', xlab = "Actual E", ylab = "Deviation from actual", ylim = c(0, 10), xlim = c(-300,-200))
points(abs(values_bottom - values_actual) ~ values_actual, type = 'l')

limits <- c(50, 5497)
limits_actual <- values_actual[limits[1]:limits[2]]
max_errors <- pmax(abs(values_top[limits[1]:limits[2]] - limits_actual), abs(values_bottom[limits[1]:limits[2]] - limits_actual))

polygon(x = c(limits_actual[1], limits_actual,  limits_actual[length(limits_actual)], limits_actual[1]), y = c(0, max_errors, 0, 0), col = rgb(1, 0, 0, alpha = 1), density = 50, lty = "dotted")

legend("top", legend = c("R+3%", "R-3%", "Possible values"), col = c('black', 'black', rgb(1,0,0,alpha = 1)), lty = c(1, 1, 5))
```

```{r E to E precision example 1, fig.align='center', fig.height = 5, fig.width = 5}
par(pty = 's', mfrow = c(1,1), mai = c(0.8, 0.8, 0.4, 0.8))
values_bottom <- E(gfp1r12_prop$R * 1.03, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = gfp1r12_prop$delta, e0 = gfp1r12_prop$e0)
values_top <- E(gfp1r12_prop$R * 0.97, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = gfp1r12_prop$delta, e0 = gfp1r12_prop$e0)
values_actual <- E(gfp1r12_prop$R,  Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, delta = gfp1r12_prop$delta, e0 = gfp1r12_prop$e0)

plot(values_top ~ values_actual, type = 'l', xlab = "Actual E", ylab = "Observed E", ylim = c(-300, -200), xlim = c(-300,-200))
points(values_bottom ~ values_actual, type = 'l')

limits <- c(100, 5497)
polygon(c(values_actual[limits[1]:limits[2]], rev(values_actual[limits[1]:limits[2]])), y = c(values_top[limits[1]:limits[2]], rev(values_bottom[limits[1]:limits[2]])), col = rgb(1, 0, 0, alpha = 1), density = 50, lty = "dotted")

legend("bottomright", legend = c("R+3%", "R-3%", "Possible values"), col = c('black', 'black', rgb(1,0,0,alpha = 1)), lty = c(1, 1, 5))
```


```{r E to difference in E_max, fig.align='center', fig.height = 5, fig.width = 5}
par(pty = 's', mfrow = c(1,1), mai = c(0.4, 0.8, 0.4, 0.8))

error_2 = Error_E(gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, e0 = gfp1r12_prop$e0, delta = gfp1r12_prop$delta, percent_error = 2)
error_3 = Error_E(gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, e0 = gfp1r12_prop$e0, delta = gfp1r12_prop$delta, percent_error = 3)
error_4 = Error_E(gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, e0 = gfp1r12_prop$e0, delta = gfp1r12_prop$delta, percent_error = 4)
colors <- coolwarm(9)

plot(error_2 ~ gfp1r12_prop$E, type = 'l', ylim = c(0, 5), xlim = c(-300, -220), col = colors[7], lwd = 2, bty = 'l', ylab = "Expected accuracy (mV)", xlab = expression(E[GSH]), main = "")
axis(side = 2, at = seq(0, 5, by = 0.1), 
     labels = FALSE, tcl = -0.2) 
axis(side = 1, at = seq(-300, -200, by = 5), 
     labels = FALSE, tcl = -0.2) 
points(error_3 ~ gfp1r12_prop$E, type = 'l', col = colors[8], lwd = 2)
points(error_4 ~ gfp1r12_prop$E, type = 'l', col = colors[9], lwd = 2)
#points(x = c(2,2), y = (c(-220, -300)), type = "l")
#points(x = c(min(error_2), min(error_2)), y = (c(-200, -300)), type = "l")


legend("top", title = "Empircal precision in R", xpd=TRUE, c("2%", "3%", "4%"), pch = "-", lwd = 4, col = c(colors[7:9]), cex = 1)
```


```{r Phase Plot 1, fig.align='center', fig.height = 5, fig.width = 5}
par(pty = 's', mfrow = c(1,1), mai = c(0.4, 0.8, 0.4, 0.8))

error_2 = Error_E(gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, e0 = gfp1r12_prop$e0, delta = gfp1r12_prop$delta, percent_error = 2)
error_3 = Error_E(gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, e0 = gfp1r12_prop$e0, delta = gfp1r12_prop$delta, percent_error = 3)
error_4 = Error_E(gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, e0 = gfp1r12_prop$e0, delta = gfp1r12_prop$delta, percent_error = 4)
colors <- coolwarm(9)

plot(gfp1r12_prop$E ~ error_2, type = 'l', xlim = c(0, 5), ylim = c(-300, -220), col = colors[7], lwd = 2, bty = 'l', xlab = "Expected accuracy (mV)", ylab = expression(E[GSH]), main = "")
axis(side = 1, at = seq(0, 5, by = 0.1), 
     labels = FALSE, tcl = -0.2) 
axis(side = 2, at = seq(-300, -200, by = 5), 
     labels = FALSE, tcl = -0.2) 
points(gfp1r12_prop$E ~ error_3, type = 'l', col = colors[8], lwd = 2)
points(gfp1r12_prop$E ~ error_4, type = 'l', col = colors[9], lwd = 2)
#points(x = c(2,2), y = (c(-220, -300)), type = "l")
#points(x = c(min(error_2), min(error_2)), y = (c(-200, -300)), type = "l")


legend("right", title = "Empircal precision in R", xpd=TRUE, c("2%", "3%", "4%"), pch = "-", lwd = 4, col = c(colors[7:9]), cex = 1)
```

```{r Phase Plot Delta, fig.align='center', fig.height = 5, fig.width = 5}
par(pty = 's', mfrow = c(1,1), mai = c(0.4, 0.8, 0.4, 0.8))

error_2 = Error_E(gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, e0 = gfp1r12_prop$e0, delta = 800, percent_error = 3)
error_3 = Error_E(gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, e0 = gfp1r12_prop$e0, delta = 1, percent_error = 3)
error_4 = Error_E(gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, e0 = gfp1r12_prop$e0, delta = 0.125, percent_error = 3)
colors <- coolwarm(9)

plot(gfp1r12_prop$E ~ error_2, type = 'l', xlim = c(0, 5), ylim = c(-500, -220), col = colors[7], lwd = 2, bty = 'l', xlab = "Expected accuracy (mV)", ylab = expression(E[GSH]), main = "")
axis(side = 1, at = seq(0, 5, by = 0.1), 
     labels = FALSE, tcl = -0.2) 
axis(side = 2, at = seq(-300, -200, by = 5), 
     labels = FALSE, tcl = -0.2) 
points(gfp1r12_prop$E ~ error_3, type = 'l', col = colors[8], lwd = 2)
points(gfp1r12_prop$E ~ error_4, type = 'l', col = colors[9], lwd = 2)
#points(x = c(2,2), y = (c(-220, -300)), type = "l")
#points(x = c(min(error_2), min(error_2)), y = (c(-200, -300)), type = "l")


legend("right", title = expression(delta), xpd=TRUE, c("8", "1", "1/8"), pch = "-", lwd = 4, col = c(colors[7:9]), cex = 1)
```


```{r Phase Plot 2, fig.align='center', fig.height = 5, fig.width = 5}
par(pty = 's', mfrow = c(1,1), mai = c(0.4, 0.8, 0.4, 0.8))


error_4 = Error_E(gfp1r12_prop$R, Rmin = gfp1r12_prop$Rmin, Rmax = gfp1r12_prop$Rmax, e0 = gfp1r12_prop$e0, delta = gfp1r12_prop$delta, percent_error = 4)
colors <- coolwarm(9)

bounds <- c(-290, -220)
plot(gfp1r12_prop$E ~ error_4, type = 'l', xlim = c(0, 5), ylim = bounds, col = colors[9], lwd = 2, bty = 'l', xlab = "Expected accuracy (mV)", ylab = expression(E[GSH]), main = "")
axis(side = 1, at = seq(0, 5, by = 0.1), 
     labels = FALSE, tcl = -0.2) 
axis(side = 2, at = seq(-300, -200, by = 1), 
     labels = FALSE, tcl = -0.2) 

points(x = c(2,2), y = (bounds), type = "l")

good_area <- data.frame(acc = subset(error_4, error_4 < 2.01),
                        E = subset(gfp1r12_prop$E, error_4 < 2.01))

polygon(c(2, good_area$acc, 2), y = c(max(good_area$E), good_area$E, min(good_area$E)), col = rgb(1, 0, 0, alpha = 1), density = 50, lty = "dotted")


```


```{r not sure}
plot(min(gfp1r12_max_prop$Error5) ~ I(gfp1r12_max_prop$Rmax/gfp1r12_max_prop$Rmin), col = colors4[2], bty = 'l',pch = 16, cex = 2, ylim = c(0, 10), xlim = c(0, 40), ylab = "Minimum Error (mV)", xlab = expression(R[Max]/R[Min]), main = "Fold-change inversely related to minimum error")
points(min(gfp1r12_iso_prop$Error5) ~ I(gfp1r12_iso_prop$Rmax/gfp1r12_iso_prop$Rmin), col = colors4[1],pch = 16, cex = 2)

legend("topright", xpd=TRUE, c("GFP1 Max", "GFP1 Iso"), pch = "-", lwd = 4, col = c(colors4[2], colors4[1]), cex = 1)

plot(min(gfp1r12_max_prop$Error5) ~ log(gfp1r12_max_prop$delta), col = colors4[2], bty = 'l',pch = 16, cex = 2, ylim = c(0, 10), xlim = c(-2, 2), ylab = "Minimum Error (mV)", xlab = expression(ln(delta)), main = "Relationship between delta and minimum error?")
points(min(gfp1r12_iso_prop$Error5) ~ log(gfp1r12_iso_prop$delta), col = colors4[1],pch = 16, cex = 2)


legend("topright", xpd=TRUE, c("GFP1 Max", "GFP1 Iso"), pch = "-", lwd = 4, col = c(colors4[2], colors4[1]), cex = 1)
```


```{r Sensitivity of E and OxD,  fig.align='center', fig.height = 5, fig.width = 5}
par(pty = 's', mfrow = c(1,1), mai = c(0.4, 0.8, 0.4, 0.8))
plot(gfp1r12_max_prop$OxD_sen ~ gfp1r12_max_prop$RDoublePrime, type = 'l', col = colors4[2], lwd = 2, bty = 'l', xlab = "R''", ylab = "Relative sensitivity of OxD", ylim = c(0, 3), main = "Normalized R -> sensitivity of fraction oxidized")
points(gfp1r12_iso_prop$OxD_sen ~ gfp1r12_iso_prop$RDoublePrime, type = 'l', col = colors4[1], lwd = 2)

legend("topright", xpd=TRUE, c("GFP1-R12 Max", "GFP1 Iso"), pch = "-", lwd = 4, col = c(colors4[2], colors4[1], colors4[3], colors4[4]), cex = 1)

plot(gfp1r12_max_prop$E_sen ~ gfp1r12_max_prop$RDoublePrime, type = 'l', col = colors4[2], lwd = 2, bty = 'l', xlab = "R''", ylab = "Relative sensitivity of E", ylim = c(0, 200), main = "Normalized R -> sensitivity of half-cell potential")
points(gfp1r12_iso_prop$E_sen ~ gfp1r12_iso_prop$RDoublePrime, type = 'l', col = colors4[1], lwd = 2, lty = 1)

legend("top", xpd=TRUE, c("GFP1-R12 Max", "GFP1-R12 Iso"), lwd = 4, col = c(colors4[2], colors4[1]), cex = 1)
```


## Error in half-cell potential readout given a 5% error in R

```{r, fig.align='center', fig.height = 5, fig.width = 5}
par(pty = 's', mfrow = c(1,1), mai = c(0.4, 0.8, 0.4, 0.8))

plot(gfp1r12_max_prop$E ~ gfp1r12_max_prop$Error5, type = 'l', xlim = c(0, 20), ylim = c(-350, -150), col = colors4[2], lwd = 2, bty = 'l', xlab = "Minimum Error", ylab = expression(E[GSH]), main = "5% error in R -> Measures of E detectable within error")
points(gfp1r12_iso_prop$E ~ gfp1r12_iso_prop$Error5, type = 'l', col = colors4[1], lwd = 2)


legend("top", xpd=TRUE, c("GFP1 Max", "GFP1 Iso"), pch = "-", lwd = 4, col = c(colors4[2], colors4[1]), cex = 1)

plot(min(gfp1r12_max_prop$Error5) ~ I(gfp1r12_max_prop$Rmax/gfp1r12_max_prop$Rmin), col = colors4[2], bty = 'l',pch = 16, cex = 2, ylim = c(0, 10), xlim = c(0, 40), ylab = "Minimum Error (mV)", xlab = expression(R[Max]/R[Min]), main = "Fold-change inversely related to minimum error")
points(min(gfp1r12_iso_prop$Error5) ~ I(gfp1r12_iso_prop$Rmax/gfp1r12_iso_prop$Rmin), col = colors4[1],pch = 16, cex = 2)

legend("topright", xpd=TRUE, c("GFP1 Max", "GFP1 Iso"), pch = "-", lwd = 4, col = c(colors4[2], colors4[1]), cex = 1)

plot(min(gfp1r12_max_prop$Error5) ~ log(gfp1r12_max_prop$delta), col = colors4[2], bty = 'l',pch = 16, cex = 2, ylim = c(0, 10), xlim = c(-2, 2), ylab = "Minimum Error (mV)", xlab = expression(ln(delta)), main = "Relationship between delta and minimum error?")
points(min(gfp1r12_iso_prop$Error5) ~ log(gfp1r12_iso_prop$delta), col = colors4[1],pch = 16, cex = 2)


legend("topright", xpd=TRUE, c("GFP1 Max", "GFP1 Iso"), pch = "-", lwd = 4, col = c(colors4[2], colors4[1]), cex = 1)
```

```{r extra}
png("rogfp1r12_R_OxD.jpg")
par(pty = 's', mfrow = c(1,1), mai = c(0.4, 0.8, 0.4, 0.8))
plot(gfp1r12_prop$OxD ~ gfp1r12_prop$R, type = 'l', xlab = "R", ylab = "OxD (Fraction Oxidized)", bty = 'l', col = colors4[1], lwd = 2)
dev.off()
```

